id: I800674D7
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T21:47:26.199994'
last_modified: '2022-05-30T21:47:26.199999'
parser: null
source_metadata:
  title: Jetsünma Muntso Rinpoche
  language: bo
  description: 'Texts by and about Mumé Yeshe Tsomo (mu med ye shes mtsho mo, b.1966),
    who is the niece of Khenchen Jigme Puntsok and renowned as an incarnation of Jetsün
    Mingyur Paldrön:'
  volume:
    fAB3F:
      title: 'The Great Treasure of a Hundred Blessings: A Prayer for the Long Life
        of Ḍākinī Muntso Rinpoche'
      base_file: fAB3F.txt
      order: 1
      parent: Long Life Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
